mode: mechanics
outdir: ../results/magnetic_cilium_3d_results_final
results_write_mode: experiment
experiment_id: final_mechanics

D: 120.0e-6
L1: 2.0e-3
L2: 2.0e-3
substrate_radius: 0.60e-3
substrate_thickness: 0.50e-3

h_cilium: 20.0e-6
h_substrate: 100.0e-6
element_degree: 2
n_steps: 10
delta: 0.55e-3
save_mechanics_frames: true
mechanics_frames_every: 2

Br: 0.10
sensor_x: 0.0
sensor_y: 0.0
sensor_z: -50.0e-6
rotate_magnetization: true
