import gc
import logging
from typing import Dict

import basix.ufl
import gmsh
import numpy as np
import ufl
from mpi4py import MPI
from petsc4py import PETSc

import dolfinx
from dolfinx import fem, io, mesh, default_scalar_type
from dolfinx.fem import petsc as fem_petsc
from dolfinx.nls import petsc as nls_petsc

from magnetic_cilium.config.params import ModelParams, TARGET_REACTION_U_N


log = logging.getLogger("magnetic_cilium_3d")


# -----------------------------------------------------------------------------
# Mesh generation
# -----------------------------------------------------------------------------


def build_gmsh_mesh_3d(params: ModelParams):
    log.info("geometry: substrate + double-layer cylindrical cilium")
    log.info("geometry: cilium radius = %.3e m", params.R)
    log.info("geometry: L1 = %.3e m, L2 = %.3e m", params.L1, params.L2)
    log.info("geometry: substrate radius = %.3e m", params.substrate_radius)
    log.info("geometry: substrate thickness = %.3e m", params.substrate_thickness)

    gmsh.initialize()
    gmsh.model.add("magnetic_cilium_3d_with_substrate")

    try:
        substrate = gmsh.model.occ.addCylinder(
            0.0, 0.0, -params.substrate_thickness,
            0.0, 0.0, params.substrate_thickness,
            params.substrate_radius,
        )
        lower = gmsh.model.occ.addCylinder(0.0, 0.0, 0.0, 0.0, 0.0, params.L1, params.R)
        upper = gmsh.model.occ.addCylinder(0.0, 0.0, params.L1, 0.0, 0.0, params.L2, params.R)

        gmsh.model.occ.fragment([(3, substrate), (3, lower), (3, upper)], [])
        gmsh.model.occ.synchronize()

        gmsh.option.setNumber("Mesh.CharacteristicLengthMin", params.h_cilium)
        gmsh.option.setNumber("Mesh.CharacteristicLengthMax", params.h_substrate)

        box_field = gmsh.model.mesh.field.add("Box")
        gmsh.model.mesh.field.setNumber(box_field, "VIn", params.h_cilium)
        gmsh.model.mesh.field.setNumber(box_field, "VOut", params.h_substrate)
        gmsh.model.mesh.field.setNumber(box_field, "XMin", -1.25 * params.R)
        gmsh.model.mesh.field.setNumber(box_field, "XMax", 1.25 * params.R)
        gmsh.model.mesh.field.setNumber(box_field, "YMin", -1.25 * params.R)
        gmsh.model.mesh.field.setNumber(box_field, "YMax", 1.25 * params.R)
        gmsh.model.mesh.field.setNumber(box_field, "ZMin", 0.0)
        gmsh.model.mesh.field.setNumber(box_field, "ZMax", params.L)
        gmsh.model.mesh.field.setAsBackgroundMesh(box_field)

        for _, point_tag in gmsh.model.getEntities(0):
            x, y, z = gmsh.model.getValue(0, point_tag, [])
            r = float(np.sqrt(x * x + y * y))
            if (-1e-12 <= z <= params.L + 1e-12) and (r <= 1.5 * params.R):
                gmsh.model.mesh.setSize([(0, point_tag)], params.h_cilium)
            else:
                gmsh.model.mesh.setSize([(0, point_tag)], params.h_substrate)

        gmsh.option.setNumber("Mesh.Algorithm3D", 1)
        gmsh.option.setNumber("Mesh.Optimize", 1)

        log.info(
            "mesh: generating tetrahedral mesh with h_cilium = %.3e m, h_substrate = %.3e m",
            params.h_cilium,
            params.h_substrate,
        )
        gmsh.model.mesh.generate(3)

        node_tags, node_coords, _ = gmsh.model.mesh.getNodes()
        node_tags = np.asarray(node_tags, dtype=np.int64)
        points = np.asarray(node_coords, dtype=np.float64).reshape(-1, 3)

        elem_types, _, elem_node_tags = gmsh.model.mesh.getElements(dim=3)
        tet_nodes = None
        for etype, enodes in zip(elem_types, elem_node_tags):
            _, dim, _, num_nodes, _, _ = gmsh.model.mesh.getElementProperties(etype)
            if dim == 3 and num_nodes == 4:
                tet_nodes = np.asarray(enodes, dtype=np.int64).reshape(-1, 4)
                break
        if tet_nodes is None:
            raise RuntimeError("No linear tetrahedral cells were generated by gmsh.")

        tag_to_local = {int(tag): i for i, tag in enumerate(node_tags)}
        cells = np.array([[tag_to_local[int(t)] for t in tet] for tet in tet_nodes], dtype=np.int64)
        log.info("mesh: gmsh nodes = %d, tetrahedra = %d", points.shape[0], cells.shape[0])
        return points, cells
    finally:
        gmsh.finalize()


def create_dolfinx_mesh_3d(points, cells):
    log.info("mesh: creating DOLFINx tetrahedral mesh")
    coordinate_element = basix.ufl.element("Lagrange", "tetrahedron", 1, shape=(3,))
    ufl_domain = ufl.Mesh(coordinate_element)
    domain = mesh.create_mesh(MPI.COMM_WORLD, cells, ufl_domain, points)

    tdim = domain.topology.dim
    domain.topology.create_connectivity(tdim - 1, tdim)
    domain.topology.create_connectivity(tdim, tdim - 1)
    domain.topology.create_connectivity(tdim, 0)

    log.info(
        "mesh: DOLFINx cells = %d, vertices = %d",
        domain.topology.index_map(tdim).size_local,
        domain.topology.index_map(0).size_local,
    )
    return domain


def extract_cells_from_domain(domain) -> np.ndarray:
    tdim = domain.topology.dim
    domain.topology.create_connectivity(tdim, 0)
    c_to_v = domain.topology.connectivity(tdim, 0)
    num_cells = domain.topology.index_map(tdim).size_local
    cells = np.zeros((num_cells, 4), dtype=np.int64)
    for c in range(num_cells):
        vertices = c_to_v.links(c)
        if len(vertices) != 4:
            raise RuntimeError("Expected tetrahedral mesh with exactly 4 vertices per cell.")
        cells[c, :] = vertices
    return cells


# -----------------------------------------------------------------------------
# Materials
# -----------------------------------------------------------------------------


def make_material_field(domain, params: ModelParams):
    log.info("tagging: assigning material ids and coefficients")
    tdim = domain.topology.dim
    Q = fem.functionspace(domain, ("DG", 0))

    material = fem.Function(Q); material.name = "material_id"
    E = fem.Function(Q); E.name = "young_modulus"
    nu = fem.Function(Q); nu.name = "poisson_ratio"

    num_cells = domain.topology.index_map(tdim).size_local
    cell_ids = np.arange(num_cells, dtype=np.int32)
    mids = mesh.compute_midpoints(domain, tdim, cell_ids)

    substrate_count = lower_count = upper_count = 0
    for c, z in zip(cell_ids, mids[:, 2]):
        dof = Q.dofmap.cell_dofs(int(c))[0]
        if z < 0.0:
            material.x.array[dof] = 0.0
            E.x.array[dof] = params.E_pdms
            nu.x.array[dof] = params.nu_pdms
            substrate_count += 1
        elif z < params.L1:
            material.x.array[dof] = 1.0
            E.x.array[dof] = params.E_pdms
            nu.x.array[dof] = params.nu_pdms
            lower_count += 1
        else:
            material.x.array[dof] = 2.0
            E.x.array[dof] = params.E_magnetic
            nu.x.array[dof] = params.nu_magnetic
            upper_count += 1

    material.x.scatter_forward(); E.x.scatter_forward(); nu.x.scatter_forward()
    log.info("tagging: substrate PDMS cells = %d", substrate_count)
    log.info("tagging: lower cilium PDMS cells = %d", lower_count)
    log.info("tagging: upper magnetic-composite cells = %d", upper_count)
    return material, E, nu


def make_material_field_from_cell_ids(domain, material_cell_ids: np.ndarray):
    Q = fem.functionspace(domain, ("DG", 0))
    material = fem.Function(Q)
    material.name = "material_id"
    num_cells = domain.topology.index_map(domain.topology.dim).size_local
    if len(material_cell_ids) != num_cells:
        raise RuntimeError(f"Material array length mismatch: got {len(material_cell_ids)}, expected {num_cells}.")
    for c in range(num_cells):
        dof = Q.dofmap.cell_dofs(int(c))[0]
        material.x.array[dof] = float(material_cell_ids[c])
    material.x.scatter_forward()
    return material


def extract_material_cell_ids(material) -> np.ndarray:
    Q = material.function_space
    num_cells = Q.mesh.topology.index_map(Q.mesh.topology.dim).size_local
    arr = np.zeros(num_cells, dtype=np.int32)
    for c in range(num_cells):
        dof = Q.dofmap.cell_dofs(int(c))[0]
        arr[c] = int(round(float(material.x.array[dof])))
    return arr


def lame_parameters(E, nu):
    mu = E / (2.0 * (1.0 + nu))
    lmbda = E * nu / ((1.0 + nu) * (1.0 - 2.0 * nu))
    return mu, lmbda


# -----------------------------------------------------------------------------
# Hyperelasticity
# -----------------------------------------------------------------------------


def neo_hookean_energy(u, E, nu):
    mu, lmbda = lame_parameters(E, nu)
    I = ufl.Identity(3)
    Fdef = I + ufl.grad(u)
    C = Fdef.T * Fdef
    Ic = ufl.tr(C)
    J = ufl.det(Fdef)
    return (mu / 2.0) * (Ic - 3.0) - mu * ufl.ln(J) + (lmbda / 2.0) * (ufl.ln(J)) ** 2


def first_piola_stress(u, E, nu):
    mu, lmbda = lame_parameters(E, nu)
    I = ufl.Identity(3)
    Fdef = I + ufl.grad(u)
    J = ufl.det(Fdef)
    FinvT = ufl.inv(Fdef).T
    return mu * (Fdef - FinvT) + lmbda * ufl.ln(J) * FinvT


def cauchy_stress(u, E, nu):
    I = ufl.Identity(3)
    Fdef = I + ufl.grad(u)
    J = ufl.det(Fdef)
    P = first_piola_stress(u, E, nu)
    return (1.0 / J) * P * Fdef.T


# -----------------------------------------------------------------------------
# Boundary conditions and mechanics solve
# -----------------------------------------------------------------------------


def locate_bottom_and_top_facets(domain, params: ModelParams):
    fdim = domain.topology.dim - 1
    bottom_facets = mesh.locate_entities_boundary(
        domain, fdim, lambda x: np.isclose(x[2], -params.substrate_thickness, atol=1e-12)
    )
    control_facets = mesh.locate_entities_boundary(
        domain, fdim, lambda x: np.isclose(x[2], params.L, atol=1e-12)
    )
    if len(bottom_facets) == 0:
        raise RuntimeError("No bottom substrate facets found.")
    if len(control_facets) == 0:
        raise RuntimeError("No top control facets found.")
    return bottom_facets, control_facets


def solve_hyperelasticity_displacement_control_3d(domain, E, nu, params: ModelParams, step_callback=None):
    log.info("model: nonlinear Neo-Hookean top-face displacement-control mechanics")
    gdim = domain.geometry.dim
    fdim = domain.topology.dim - 1
    bottom_facets, control_facets = locate_bottom_and_top_facets(domain, params)

    log.info("BC: bottom substrate facets = %d", len(bottom_facets))
    log.info("BC: top control facets = %d", len(control_facets))

    V = fem.functionspace(domain, ("Lagrange", params.element_degree, (gdim,)))
    log.info("space: vector P%d global dofs = %d", params.element_degree, V.dofmap.index_map.size_global * V.dofmap.index_map_bs)

    zero = default_scalar_type(0.0)
    bcs = []
    for i in range(3):
        bottom_dofs_i = fem.locate_dofs_topological(V.sub(i), fdim, bottom_facets)
        bcs.append(fem.dirichletbc(zero, bottom_dofs_i, V.sub(i)))

    control_ux = fem.Constant(domain, default_scalar_type(0.0))
    control_dofs_x = fem.locate_dofs_topological(V.sub(0), fdim, control_facets)
    if len(control_dofs_x) == 0:
        raise RuntimeError("No x-dofs found on top control facets.")
    bcs.append(fem.dirichletbc(control_ux, control_dofs_x, V.sub(0)))

    u = fem.Function(V); u.name = "displacement"
    du = ufl.TrialFunction(V)
    v = ufl.TestFunction(V)

    Pi = neo_hookean_energy(u, E, nu) * ufl.dx
    residual = ufl.derivative(Pi, u, v)
    jacobian = ufl.derivative(residual, u, du)

    problem = fem_petsc.NewtonSolverNonlinearProblem(residual, u, bcs=bcs, J=jacobian)
    solver = nls_petsc.NewtonSolver(domain.comm, problem)
    solver.atol = 1e-7
    solver.rtol = 1e-6
    solver.max_it = 25
    solver.convergence_criterion = "incremental"

    ksp = solver.krylov_solver
    ksp.setType(PETSc.KSP.Type.CG)
    pc = ksp.getPC(); pc.setType(PETSc.PC.Type.GAMG)
    ksp.setTolerances(rtol=1e-6, atol=1e-10, max_it=1000)

    log.info("BC: final top displacement delta_x = %.6e m", params.delta_x)
    log.info("solve: displacement continuation steps = %d", params.n_steps)

    for step in range(1, params.n_steps + 1):
        alpha = step / params.n_steps
        control_ux.value = default_scalar_type(alpha * params.delta_x)
        n_iter, converged = solver.solve(u)
        u.x.scatter_forward()
        log.info(
            "nonlinear step %02d/%02d: delta_x = %.6e m, Newton iters = %d, converged = %s",
            step, params.n_steps, alpha * params.delta_x, n_iter, converged,
        )
        if step_callback is not None:
            step_callback(
                step=step,
                total_steps=params.n_steps,
                alpha=alpha,
                displacement=u,
                domain=domain,
                params=params,
                newton_iterations=n_iter,
                converged=bool(converged),
            )
        if not converged:
            raise RuntimeError(f"Newton did not converge at step {step}/{params.n_steps}")

    local_max_ux = np.max(np.real(u.x.array[control_dofs_x]))
    max_ux = domain.comm.allreduce(local_max_ux, op=MPI.MAX)
    reaction_force_x = compute_reaction_force_x(domain, u, E, nu, control_facets)

    log.info("postprocess: max top u_x = %.9e m", max_ux)
    log.info("postprocess: reaction force x = %.9e N", reaction_force_x)
    log.info("postprocess: reaction force x = %.9e uN", reaction_force_x * 1e6)
    return u, max_ux, reaction_force_x, bottom_facets, control_facets


def compute_reaction_force_x(domain, u, E, nu, control_facets):
    fdim = domain.topology.dim - 1
    values = np.ones(len(control_facets), dtype=np.int32)
    order = np.argsort(control_facets)
    control_tags = mesh.meshtags(domain, fdim, control_facets[order], values[order])
    ds = ufl.Measure("ds", domain=domain, subdomain_data=control_tags)
    N = ufl.FacetNormal(domain)
    P = first_piola_stress(u, E, nu)
    e_x = ufl.as_vector((1.0, 0.0, 0.0))
    reaction_form = fem.form(ufl.dot(P * N, e_x) * ds(1))
    local_reaction = fem.assemble_scalar(reaction_form)
    reaction = domain.comm.allreduce(local_reaction, op=MPI.SUM)
    return abs(reaction)


# -----------------------------------------------------------------------------
# Diagnostics
# -----------------------------------------------------------------------------


def get_interpolation_points(function_space):
    points = function_space.element.interpolation_points
    return points() if callable(points) else points


def interpolate_scalar_DG0(domain, expr, name: str):
    Q = fem.functionspace(domain, ("DG", 0))
    q = fem.Function(Q); q.name = name
    expression = fem.Expression(expr, get_interpolation_points(Q))
    cells = np.arange(domain.topology.index_map(domain.topology.dim).size_local, dtype=np.int32)
    try:
        q.interpolate(expression, cells)
    except TypeError:
        q.interpolate(expression)
    q.x.scatter_forward()
    return q


def minmax_function(domain, f):
    arr = np.real(f.x.array)
    local_min = float(np.min(arr)) if arr.size else np.inf
    local_max = float(np.max(arr)) if arr.size else -np.inf
    return domain.comm.allreduce(local_min, op=MPI.MIN), domain.comm.allreduce(local_max, op=MPI.MAX)


def compute_J_field(domain, u):
    I = ufl.Identity(3)
    Fdef = I + ufl.grad(u)
    J = interpolate_scalar_DG0(domain, ufl.det(Fdef), "J_detF")
    J_min, J_max = minmax_function(domain, J)
    return J, J_min, J_max


def compute_von_mises_field(domain, u, E, nu):
    sigma = cauchy_stress(u, E, nu)
    I = ufl.Identity(3)
    s = sigma - (1.0 / 3.0) * ufl.tr(sigma) * I
    vm = interpolate_scalar_DG0(domain, ufl.sqrt((3.0 / 2.0) * ufl.inner(s, s)), "von_mises_DG0")
    vm_min, vm_max = minmax_function(domain, vm)
    return vm, vm_min, vm_max


def compute_material_volumes(domain, material) -> Dict[int, float]:
    dx = ufl.Measure("dx", domain=domain)
    volumes = {}
    for mat_id in (0, 1, 2):
        indicator = ufl.conditional(ufl.lt((material - float(mat_id)) * (material - float(mat_id)), 0.25), 1.0, 0.0)
        local_vol = fem.assemble_scalar(fem.form(indicator * dx))
        volumes[mat_id] = domain.comm.allreduce(local_vol, op=MPI.SUM)
    return volumes


def evaluate_displacement_at_geometry_vertices(domain, u):
    gdim = domain.geometry.dim
    V1 = fem.functionspace(domain, ("Lagrange", 1, (gdim,)))
    u1 = fem.Function(V1)
    u1.name = "displacement_P1_for_magnetics"
    u1.interpolate(u)
    u1.x.scatter_forward()
    bs = V1.dofmap.index_map_bs
    u_values = np.real(u1.x.array).reshape((-1, bs))[:, :3]
    num_vertices = domain.topology.index_map(0).size_local
    if u_values.shape[0] != num_vertices:
        raise RuntimeError("P1 displacement dof count does not match geometry vertex count.")
    return u_values


def log_mesh_resolution_warning(params: ModelParams) -> None:
    elements_across_diameter = params.D / params.h_cilium
    log.info("mesh quality: elements across cilium diameter D/h_cilium = %.2f", elements_across_diameter)
    if elements_across_diameter < 4.0:
        log.warning("Cilium mesh is very coarse across diameter: D/h_cilium = %.2f. Reaction force may be unreliable.", elements_across_diameter)


def validate_result_quality(params: ModelParams, result: Dict) -> None:
    if "J_min" in result and result["J_min"] <= 0.0:
        raise RuntimeError(f"Invalid deformation: det(F) <= 0, min J = {result['J_min']}")
    if "reaction_force_x_uN" in result:
        rel_error = abs(result["reaction_force_x_uN"] - TARGET_REACTION_U_N) / TARGET_REACTION_U_N
        if result.get("study", "").startswith("final") and rel_error > 0.15:
            log.warning("Final run is far from target reaction: reaction = %.3f uN, target = %.3f uN, error = %.1f%%",
                        result["reaction_force_x_uN"], TARGET_REACTION_U_N, 100.0 * rel_error)


def save_results(domain, uh, material, E, nu, J_field, von_mises, params: ModelParams):
    import os
    log.info("output: writing VTK/PVD results")
    os.makedirs(params.outdir, exist_ok=True)
    vtk_path = os.path.join(params.outdir, "magnetic_cilium_3d.pvd")
    uh.name = "displacement"; material.name = "material_id"; E.name = "young_modulus"; nu.name = "poisson_ratio"
    J_field.name = "J_detF"; von_mises.name = "von_mises_DG0"
    with io.VTKFile(domain.comm, vtk_path, "w") as vtk:
        vtk.write_mesh(domain)
        vtk.write_function([uh, material, E, nu, J_field, von_mises])
    log.info("output: saved %s", vtk_path)
    return vtk_path
